# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sequence.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0esequence.proto\"\x1f\n\x0fSequenceRequest\x12\x0c\n\x04\x62its\x18\x01 \x01(\x05\"!\n\rSequenceReply\x12\x10\n\x08sequence\x18\x01 \x01(\x03\x32<\n\x08Sequence\x12\x30\n\nLiveStream\x12\x10.SequenceRequest\x1a\x0e.SequenceReply0\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sequence_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SEQUENCEREQUEST._serialized_start=18
  _SEQUENCEREQUEST._serialized_end=49
  _SEQUENCEREPLY._serialized_start=51
  _SEQUENCEREPLY._serialized_end=84
  _SEQUENCE._serialized_start=86
  _SEQUENCE._serialized_end=146
# @@protoc_insertion_point(module_scope)
