# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from easyflake.grpc import sequence_pb2 as sequence__pb2


class SequenceStub(object):
    """The sequence service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LiveStream = channel.unary_stream(
                '/Sequence/LiveStream',
                request_serializer=sequence__pb2.SequenceRequest.SerializeToString,
                response_deserializer=sequence__pb2.SequenceReply.FromString,
                )


class SequenceServicer(object):
    """The sequence service definition.
    """

    def LiveStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SequenceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LiveStream': grpc.unary_stream_rpc_method_handler(
                    servicer.LiveStream,
                    request_deserializer=sequence__pb2.SequenceRequest.FromString,
                    response_serializer=sequence__pb2.SequenceReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Sequence', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Sequence(object):
    """The sequence service definition.
    """

    @staticmethod
    def LiveStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Sequence/LiveStream',
            sequence__pb2.SequenceRequest.SerializeToString,
            sequence__pb2.SequenceReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
